version: '3.8'

services:
  django:
    build: ./backend/booking_spaceses
    env_file: .env
    command: >
      bash -c "python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0.0.0.0:8000 booking_spaceses.wsgi:application"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - app-network
    restart: unless-stopped

  react:
    build: 
      context: ./frontend/booking_front
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=https://booking.dixer.keenetic.link/api

  nginx:
    image: nginx:alpine
    ports:
      - "192.168.1.79:80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - ./backend:/app/backend
      - ./frontend/booking_front/build:/usr/share/nginx/html
      - media_volume:/usr/share/nginx/media
    depends_on:
      - django
      - react
    networks:
      - app-network
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:

networks:
  app-network:
    driver: bridge