version: '3.8'

services:
  backend:
    build: ./backend
    command: gunicorn --bind 0.0.0.0:8000 booking_spaceses.wsgi:application
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5432/${POSTGRES_DB}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
    networks:
      - booking_network

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    networks:
      - booking_network

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./frontend/booking_front/build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - booking_network

volumes:
  static_volume:
  media_volume:

networks:
  booking_network:
    driver: bridge